package com.ktaha.currencyconverter.models

data class Rates(
    val AUD: Double,
    val BGN: Double,
    val BRL: Double,
    val CAD: Double,
    val CHF: Double,
    val CNY: Double,
    val CZK: Double,
    val DKK: Double,
    val EUR: Double,
    val GBP: Double,
    val HKD: Double,
    val HRK: Double,
    val HUF: Double,
    val IDR: Double,
    val ILS: Double,
    val INR: Double,
    val ISK: Double,
    val JPY: Double,
    val KRW: Double,
    val MXN: Double,
    val MYR: Double,
    val NOK: Double,
    val NZD: Double,
    val PHP: Double,
    val PLN: Double,
    val RON: Double,
    val RUB: Double,
    val SEK: Double,
    val SGD: Double,
    val THB: Double,
    val TRY: Double,
    val USD: Double,
    val ZAR: Double
) {
    fun getCurrenciesMap(): Map<String, Double> {
        return mapOf<String, Double>(
                "AUD" to AUD,
                "BGN" to BGN,
                "BRL" to BRL,
                "CAD" to CAD,
                "CHF" to CHF,
                "CNY" to CNY,
                "CZK" to CZK,
                "DKK" to DKK,
                "EUR" to EUR,
                "GBP" to GBP,
                "HKD" to HKD,
                "HRK" to HRK,
                "HUF" to HUF,
                "IDR" to IDR,
                "ILS" to ILS,
                "INR" to INR,
                "ISK" to ISK,
                "JPY" to JPY,
                "KRW" to KRW,
                "MXN" to MXN,
                "MYR" to MYR,
                "NOK" to NOK,
                "NZD" to NZD,
                "PHP" to PHP,
                "PLN" to PLN,
                "RON" to RON,
                "RUB" to RUB,
                "SEK" to SEK,
                "SGD" to SGD,
                "THB" to THB,
                "TRY" to TRY,
                "USD" to USD,
                "ZAR" to ZAR
        )
    }

    fun getCurrenciesArray(): Array<String> {
        return arrayOf("AUD",
                "BGN",
                "BRL",
                "CAD",
                "CHF",
                "CNY",
                "CZK",
                "DKK",
                "EUR",
                "GBP",
                "HKD",
                "HRK",
                "HUF",
                "IDR",
                "ILS",
                "INR",
                "ISK",
                "JPY",
                "KRW",
                "MXN",
                "MYR",
                "NOK",
                "NZD",
                "PHP",
                "PLN",
                "RON",
                "RUB",
                "SEK",
                "SGD",
                "THB",
                "TRY",
                "USD",
                "ZAR")
    }
}